@startuml classes

class Article {
    - name: str
    - description: str
    - category: Category
    - brand: Brand

}

class Receipt_Type {
    - name: str
    - description: str
    - type: int // 1: in, 0: transfer, -1: out
}

class Receipt {
    - header: Receipt_Header
    - contents: Receipt_Content
    - footer: Receipt_Footer
}

class Receipt_Header {
    - submission_date: datetime
    - type: Receipt_type

}

class Receipt_Content {
    - articles: Article
    - quantity: float

}

class Receipt_Footer {
    - total: float

}

Receipt_Header --> Receipt
Receipt_Content --> Receipt
Receipt_Footer --> Receipt

class Category {
    - name: str
    - description: str
}

class Brand {
    - name: str
    - description: str
}

class Stock {
    - contents: Receipt_Content
}


Stock --> Article
Category --> Article
Brand --> Article
Receipt_Type --> Receipt